server.port: 7002
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trash
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
